const surprisePrompts = [
  "What is your favorite book and why?",
  "Describe a memorable trip you have taken.",
  "What is your dream job?",
  "If you could have dinner with anyone, living or dead, who would it be?",
  "What is your favorite hobby?",
  "Describe a time you overcame a challenge.",
  "What is your favorite movie and why?",
  "If you could live anywhere in the world, where would it be?",
  "What is your favorite childhood memory?",
  "Describe a time you helped someone.",
  "What is your favorite food?",
  "If you could have any superpower, what would it be?",
  "What is your favorite season and why?",
  "Describe a time you learned something new.",
  "What is your favorite holiday?",
  "If you could meet any historical figure, who would it be?",
  "What is your favorite animal?",
  "Describe a time you achieved a goal.",
  "What is your favorite sport?",
  "If you could travel back in time, where would you go?",
  "What is your favorite TV show?",
  "Describe a time you made a new friend.",
  "What is your favorite type of music?",
  "If you could change one thing about the world, what would it be?",
  "What is your favorite way to relax?",
  "Describe a time you felt proud of yourself.",
  "What is your favorite type of weather?",
  "If you could learn any skill, what would it be?",
  "What is your favorite type of art?",
  "Describe a time you faced a fear.",
  "What is your favorite type of exercise?",
  "If you could invent something, what would it be?",
  "What is your favorite type of technology?",
  "Describe a time you made a mistake and learned from it.",
  "What is your favorite type of clothing?",
  "If you could have any job for a day, what would it be?",
  "What is your favorite type of transportation?",
  "Describe a time you felt inspired.",
  "What is your favorite type of architecture?",
  "If you could have any pet, what would it be?",
  "What is your favorite type of landscape?",
  "Describe a time you felt grateful.",
  "What is your favorite type of plant?",
  "If you could visit any planet, which one would it be?",
  "What is your favorite type of drink?",
  "Describe a time you felt happy.",
  "What is your favorite type of dessert?",
  "If you could speak any language, what would it be?",
  "What is your favorite type of book genre?",
  "Describe a time you felt loved.",
  "What is your favorite type of flower?",
  "If you could play any musical instrument, what would it be?",
  "What is your favorite type of game?",
  "Describe a time you felt excited.",
  "What is your favorite type of festival?",
  "If you could be any character from a book or movie, who would it be?",
  "What is your favorite type of dance?",
  "Describe a time you felt relaxed.",
  "What is your favorite type of vacation?",
  "If you could create a new holiday, what would it be?",
  "What is your favorite type of fruit?",
  "Describe a time you felt adventurous.",
  "What is your favorite type of vegetable?",
  "If you could redesign your home, what would it look like?",
  "What is your favorite type of snack?",
  "Describe a time you felt creative.",
  "What is your favorite type of car?",
  "If you could have any talent, what would it be?",
  "What is your favorite type of jewelry?",
  "Describe a time you felt peaceful.",
  "What is your favorite type of furniture?",
  "If you could change one thing about yourself, what would it be?",
  "What is your favorite type of fabric?",
  "Describe a time you felt confident.",
  "What is your favorite type of footwear?",
  "If you could have any job in the world, what would it be?",
  "What is your favorite type of accessory?",
  "Describe a time you felt curious.",
  "What is your favorite type of building?",
  "If you could visit any fictional world, where would it be?",
  "What is your favorite type of park?",
  "Describe a time you felt determined.",
  "What is your favorite type of museum?",
  "If you could have any piece of art, what would it be?",
  "What is your favorite type of historical site?",
  "Describe a time you felt joyful.",
  "What is your favorite type of beach?",
  "If you could have any job in the future, what would it be?",
  "What is your favorite type of mountain?",
  "Describe a time you felt motivated.",
  "What is your favorite type of river?",
  "If you could have any type of garden, what would it be?",
  "What is your favorite type of lake?",
  "Describe a time you felt hopeful.",
  "What is your favorite type of forest?",
  "If you could have any type of house, what would it be?",
  "What is your favorite type of desert?",
  "Describe a time you felt fulfilled.",
  "What is your favorite type of city?",
  "If you could have any type of job, what would it be?",
  "What is your favorite type of countryside?",
  "Describe a time you felt content.",
];

function getRandomSurprisePrompt() {
  const randomIndex = Math.floor(Math.random() * surprisePrompts.length);
  return surprisePrompts[randomIndex];
}

const surprise = getRandomSurprisePrompt;
console.log(surprise);

export default surprise;
